name: mazzica
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  liquid_glass_widgets: ^1.5.0
  just_audio: ^0.10.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^8.2.1
  shimmer: ^4.0.0
  flutter_arc_text: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/